services:

  app:
    image: python-rest
    build: ./app
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - 5000:5000
    networks:
      - app-net

  postgres-db:
    image: postgres:13-alpine
    restart: always
    env_file:
      - ./postgres.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -q -U $${POSTGRES_USER}"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_interval: 30s
    networks:
      - app-net


networks:
  app-net:
volumes:
  postgres-db:
